name: dottr
description: "A personal markdown journal with Git sync"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  yaml: ^3.1.3
  flutter_markdown: ^0.7.7
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^6.1.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  collection: ^1.19.1
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  shared_preferences: ^2.3.4
  archive: ^4.0.2
  file_picker: ^8.1.7
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
